### ISSUE TITLE
io.fabric8.docker.api.model.DockerConfig["stackOrchestrator"])

### ISSUE THREAD

**Issue by m0schaefer** [fabric8io/docker-client#112]
With docker-client 1.3.1 and docker for windows (Server Version: 18.06.1-ce) I observe this error:

ERROR io.fabric8.docker.client.Config - Could not load docker config file from D:\Users\axiaz\.docker\config.json
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "stackOrchestrator" (class io.fabric8.docker.api.model.DockerConfig), not marked as ignorable (one known property: "auths"])
  at [Source: D:\Users\axiaz\.docker\config.json; line: 3, column: 25] (through reference chain: io.fabric8.docker.api.model.DockerConfig["stackOrchestrator"])
 	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
 	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264)
 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2620)
	at io.fabric8.docker.client.Config.tryDockerConfig(Config.java:223)
	at io.fabric8.docker.client.Config.<init>(Config.java:119)
 	at io.fabric8.docker.client.Config.<init>(Config.java:125)
 	at io.fabric8.docker.client.EditableConfig.<init>(EditableConfig.java:15)
 	at io.fabric8.docker.client.ConfigBuilder.build(ConfigBuilder.java:86)

config.json:
{
  "auths": {},
  "stackOrchestrator": "swarm"
}

**Comment by m0schaefer** [comment]
Same issues as #106
