### ISSUE TITLE
Deleting a docker image throws exception

### ISSUE THREAD

**Issue by manjulaRathnayaka** [fabric8io/docker-client#32]
I have tried out deleting docker images as below using 1.0.4 version of docker-client.
`String deleted = dockerClient.image().withName("192.168.16.2:5000/manjula/cron").delete().andPrune().getDeleted();`

It throws below exception. Tried out with force, withNoPrune options as well and it gave similar exception. Let me know If I make a mistake when calling docker delete operation.
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
 at [Source: buffer(com.squareup.okhttp.internal.http.Http1xStream$FixedLengthSource@43907e05).inputStream(); line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3451)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3429)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchToken(UTF8StreamJsonParser.java:2750)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2587)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:841)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:737)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2810)
	at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:216)
	at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:191)
	at io.fabric8.docker.client.impl.OperationSupport.handleDelete(OperationSupport.java:155)
	at io.fabric8.docker.client.impl.ImageDelete.doDelete(ImageDelete.java:48)

**Comment by iocanel** [comment]
@manjulaRathnayaka: Thanks for reporting. I pushed a fix on master and will release soon.
