### ISSUE TITLE
"json: cannot unmarshal object" when starting a container

### ISSUE THREAD

**Issue by chamilad** [fabric8io/docker-client#76]
I'm trying to spawn a container using the following piece of code on the local machine (`DockerClient` from environment variables).

```java
DockerClient client = getDockerClient(dockerEnv);
ContainerCreateResponse container = client.container().createNew().withImage(serviceName.toLowerCase() + ":latest").done();
client.container().withName(container.getId()).logs().writingOutput(outputStream).writingError(outputStream).display();
client.container().withName(container.getId()).start();
```

However, at line 2, the client throws the following error, when connecting to the Docker API.

```
Failure executing: POST at: http://localhost/containers/create. Status:500. Message: Internal Server Error. Body: {"message":"json: cannot unmarshal object into Go value of type []mount.Mount"}
```

During debugging, it looks like the request that is going to the Docker API has a JSON object for `mounts` rather than an array like the API expects. Is this because of incompatibility in the API? I tried adding a pseudo mount as well, without success. 

```bash
$ docker --version
Docker version 1.13.0, build 49bf474
```

**Comment by iocanel** [comment]
I'll have a look asap.

**Comment by iocanel** [comment]
In the examples project we have and example that creates a container using code almost identical to yours and it works in 1.13.0 with no issues.

Now regarding your comment, the docker api doesn't seem to expect an array, but a map:
https://github.com/docker/docker/blob/4acf6aa4568abb8f5e9872b6804d0df4b80f41f7/api/types/container/config.go#L52-L52 

An array is only used in the response.

The only thing that seems out of place, is the name, that should be volumes instead of mounts.

**Comment by iocanel** [comment]
Added minor enhancements to the example and fixed the wrong field name.
I think that your code so work eitherways.

Can you tell me if the example works for you?

**Comment by chamilad** [comment]
Thanks for the response @iocanel! However the container run example doesn't quite seem to work for me yet. I'm getting the following error while trying to run the example, after a successful build example run. 

```
$ ./examples/target/hawt-app/bin/run.sh ContainerStartExample unix:///var/run/docker.sock myimage
Could not invoke main on:ContainerStartExample
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.fabric8.docker.examples.Main.main(Main.java:42)
Caused by: io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/containers/bf26be50eed7903b4d80a067a4657c55dc691d0fa3a78a44c3d6abc8a97a606d/start. Status:500. Message: Internal Server Error. Body: {"message":"oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/local/bin/hello.sh\\\": stat /usr/local/bin/hello.sh: not a directory\"\n: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}

        at io.fabric8.docker.client.impl.OperationSupport.requestFailure(OperationSupport.java:276)
        at io.fabric8.docker.client.impl.OperationSupport.assertResponseCodes(OperationSupport.java:260)
        at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:212)
        at io.fabric8.docker.client.impl.ContainerNamedOperationImpl.start(ContainerNamedOperationImpl.java:154)
        at io.fabric8.docker.client.impl.ContainerNamedOperationImpl.start(ContainerNamedOperationImpl.java:45)
        at io.fabric8.docker.examples.ContainerStartExample.main(ContainerStartExample.java:84)
        ... 5 more
```

However, the initial code I'm trying to work with kind of progressed to the next issue. I'm able to start the container. However the logs are not getting redirected to the specified OutputStream. 

``` java
DockerClient client = getDockerClient(dockerEnv);
ContainerCreateResponse container = client.container().createNew().withImage(serviceName.toLowerCase() + ":latest").done();
OutputHandle logHandle = client.container().withName(container.getId()).logs().writingOutput(System.out).writingError(System.out).display();
client.container().withName(container.getId()).start();
System.out.println("Container started: " + container.getId());

...
return IOUtils.toString(logHandle.getOutput(), "UTF-8");
```

I'm getting the following error at line 3.

```
2017-02-02 07:16:43 ERROR InputStreamReader:85 - Error while pumping stream.
java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:59)
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
        at io.fabric8.docker.client.utils.DockerStreamPumper.run(DockerStreamPumper.java:61)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Container started: b7029320875bdd4960cc575caff0d11c2f1cf45c4d865a3b7c5669deff19b705

```

**Comment by chamilad** [comment]
I got the example running after making the following changes to `image1` Dockerfile.

``` git
diff --git a/examples/src/main/resources/image1/Dockerfile b/examples/src/main/resources/image1/Dockerfile
index 35bd182..45b0c5e 100644
--- a/examples/src/main/resources/image1/Dockerfile
+++ b/examples/src/main/resources/image1/Dockerfile
@@ -1,4 +1,5 @@
 #image1
-FROM scratch
-COPY bin/hello.sh /usr/local/bin
-CMD ["/usr/local/bin/hello.sh"]
\ No newline at end of file
+FROM alpine
+COPY bin/hello.sh /usr/local/bin/
+RUN chmod +x /usr/local/bin/hello.sh
+CMD ["/usr/local/bin/hello.sh"]
```

**Comment by chamilad** [comment]
Looks like the EOFError is the same as the last error mentioned in #62 .

**Comment by chamilad** [comment]
@iocanel Could you please do a patch release for the above fix done?

**Comment by chamilad** [comment]
@iocanel Ping! :)

**Comment by chamilad** [comment]
Closing as release 1.2.2 contains the above fix.
